#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := shared_resource_using_semaphore

include $(IDF_PATH)/make/project.mk
